### ISSUE TITLE
I found a few possible errors, one which is breaking for me

### ISSUE THREAD

**Issue by ADRFranklin** [mnahkies/openapi-code-generator#117]
So I ignored a few of the issues since, this project is still early, and they were only type issues that I could work around, but with version 0.3.0 another issue has cropped up that breaks things for me.

So the major issue that breaks things for me now, is the fact then after updating to 0.3.0 I am presented with
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './errors' is not defined by "exports" in /workspace/node_modules/@nahkies/typescript-koa-runtime/package.json
```

and the small but workaround issues that I have found since day one of using this, is also related in a way to the above, but not caused by it. 
```
Cannot find module '@nahkies/typescript-koa-runtime/server' or its corresponding type declarations.ts(2307)
Cannot find module '@nahkies/typescript-koa-runtime/zod' or its corresponding type declarations.ts(2307)
```
it seems the runtime has no issues with these paths, but typescript does, and adding `/src/` after `@nahkies/typescript-koa-runtime` path fixes the typescript issues, so it's just a simple path rewrite that needs to happen for the typescript types.

One last possible issue that I think you overlooked was you are linking `joi` definitions for `zod`.
https://github.com/mnahkies/openapi-code-generator/blob/6d6183abf264f085eec4cb416bd8e50db11432e6/packages/typescript-koa-runtime/package.json#L37

It's possible one or more of these issues are related to my setup, so do let me know, thanks.

**Comment by mnahkies** [comment]
Raised #119 to address the `.d.ts` issue, though it _should_ be a red herring as by design the public API to the `zod` and `joi` portions of the runtime is expected to be identical.

For the:
```
Cannot find module '@nahkies/typescript-koa-runtime/server' or its corresponding type declarations.ts(2307)
Cannot find module '@nahkies/typescript-koa-runtime/zod' or its corresponding type declarations.ts(2307)
```

It would be helpful to see your `tsconfig.json` and the typescript version - my best guess is it will be caused by the `moduleResolution` parameter ([docs](https://www.typescriptlang.org/tsconfig#moduleResolution)). I'm fairly certain it needs to be:
```
"moduleResolution": "Node16",
```
and would recommend using https://github.com/tsconfig/bases/tree/main#node-20-tsconfigjson or equivalent as a base configuration which sets this by default

**Comment by ADRFranklin** [comment]
```ts
{
  "compilerOptions": {
    /* Base Options */
    "esModuleInterop": true,
    "skipLibCheck": true,
    "target": "esnext",
    // "verbatimModuleSyntax": false,
    "allowJs": true,
    "resolveJsonModule": true,
    "moduleDetection": "force",
    /* Strictness */
    "strict": true,
    "noUncheckedIndexedAccess": true,
    /* If transpiling with Typescript */
    "moduleResolution": "node",
    "module": "commonjs",
    "outDir": "dist",
    "sourceMap": true,
    "lib": [
      "es2022"
    ],
    /* Others */
    "checkJs": false,
    "noEmitOnError": true,
    "rootDir": ".",
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "declaration": true,
    "strictNullChecks": true,
    "pretty": true,
    "noEmit": false,
    "declarationMap": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "preserveConstEnums": true,
    "importHelpers": true,
    "noErrorTruncation": true,
    "baseUrl": ".",
    "paths": {
      "@/*": [
        "./src/*"
      ],
      "@nahkies/typescript-koa-runtime/*": [
        "../../node_modules/@nahkies/typescript-koa-runtime/dist/*"
      ],
    },
    "typeRoots": [
      "../../node_modules/@types",
      "./src/types",
    ],
    "types": [],
  },
  "exclude": [
    "node_modules",
    "dist",
    "tests"
  ],
  "include": [
    "./src/**/*"
  ]
}
```

I've added a types workaround for your package, which fixed the issues in this, but as requested here is my tsconfig.json file. I can't remember what I based this tsconfig off, but it was a year ago.

**Comment by mnahkies** [comment]
Based on the above config, this was likely due to `"moduleResolution"` being set to `Node` instead of `Node16` (probably `bundler` / `nodenext` would also work) - which is necessary for the `exports` field of `package.json` like https://github.com/mnahkies/openapi-code-generator/blob/acebcd931b8da07f0db9bca247c995c83576420b/packages/typescript-koa-runtime/package.json#L19-L40 to work correctly

ref: https://www.typescriptlang.org/tsconfig/#moduleResolution
